server:
  port: 8090

spring:
  application:
    name: simplewebresource
  threads:
    virtual:
      enabled: true
  #security:
  #  oauth2:
  #    resourceserver:
  #      jwt:
  #        issuer-uri: ${auth.server.uri}
